### ISSUE TITLE
Solve Reporter error: Service stays idle when no data is sent from registry

### ISSUE THREAD

**Issue by alesancor1** [governify/reporter#16]
Having refactored reporter code, it turns out the execution stops randomly at some point due to registry not sending data to reporter, since reporter now uses a stream to pipe the data through `on.('data', <function>)` handler. The stream is never ended because registry never returns a response from computer, even if it fails to get the computations.

NOTE: Every time this issue occurs, registry requests the computation to computer and it returns 202 code until it (registry) eventually times out and returns nothing to reporter, which keeps waiting indefinitely.

**Comment by alesancor1** [comment]
Having refactored reporter code, it turns out the execution stops randomly at some point due to registry not sending data to reporter, since reporter now uses a stream to pipe the data through `on.('data', <function>)` handler. The stream is never ended because registry never returns a response from computer, even if it fails to get the computations.

NOTE: Every time this issue occurs, registry requests the computation to computer and it returns 202 code until it (registry) eventually times out and returns nothing to reporter, which keeps waiting indefinitely.

**Comment by borjar20** [comment]
To solve this problem, when initializing the promise where the registry is called, we declare a timeout of 2 minutes (normal flow last about 1.5 minutes) so that in case the normal flow does not finish, it is resolved prematurely showing an error message and continuing with the subsequent periods.

**Comment by borjar20** [comment]
Once solved this error the next step is [Collector dynamic error](https://github.com/governify/collector-dynamic/issues/7)
